### ISSUE TITLE
 use of undeclared identifier 'x264_bit_depth'

### ISSUE THREAD

**Issue by harlanc** [ksvc/FFmpeg#3]
libavcodec/libx264.c:282:9: error: use of undeclared identifier 'x264_bit_depth'
    if (x264_bit_depth > 8)
        ^
libavcodec/libx264.c:892:9: error: use of undeclared identifier 'x264_bit_depth'
    if (x264_bit_depth == 8)
        ^
libavcodec/libx264.c:894:14: error: use of undeclared identifier 'x264_bit_depth'
    else if (x264_bit_depth == 9)
             ^
libavcodec/libx264.c:896:14: error: use of undeclared identifier 'x264_bit_depth'
    else if (x264_bit_depth == 10)
             ^

**Comment by songyu719** [comment]
我也遇到了这个问题！

**Comment by harlanc** [comment]
自己声明一个变量就编译通过了

**Comment by songyu719** [comment]
@harlanc  求指教

**Comment by harlanc** [comment]
int x264_bit_depth; 就行了

**Comment by harlanc** [comment]
编译能过，不知道功能正不正常

**Comment by songyu719** [comment]
@harlanc  我正在编译 你试没试功能嘛？

**Comment by songyu719** [comment]
@harlanc  我测试了一下 H265正常的 没什么问题 H264 我没试

**Comment by harlanc** [comment]
你是推rtmp的h265直播流么？用的什么播放器？

**Comment by songyu719** [comment]
@harlanc https://github.com/NodeMedia/react-native-nodemediaclient 这个播放器

**Comment by harlanc** [comment]
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                             8            117             44            423
Objective C                      5             73             35            263
Markdown                         2             48              0            223
JavaScript                       3             26             18            155
C/C++ Header                     3             13             21             32
Gradle                           1              7              0             23
JSON                             1              0              0             11
XML                              2              0              0              5
ProGuard                         1              3             18              0
-------------------------------------------------------------------------------
SUM:                            26            287            136           1135

怎么代码量这么少？用到第三方库了么？你是这家公司的啊？

**Comment by songyu719** [comment]
这个是React-Native的

**Comment by q191201771** [comment]
遇到同样的问题，  
我的环境下，查看x264的头文件`/usr/local/include/x264_config.h`  
发现有`#define X264_BIT_DEPTH     0`  
于是我把编译报错的`x264_bit_depth `全部换成了大写的`X264_BIT_DEPTH`  
成功编译了，并且编译得到的ffmpeg和ffplay的h264和h265的功能看起来都是正常的  

上面有同学说自己声明了`x264_bit_depth`变量，应该也可以，但建议将它的初始值设置为0  

写了一篇文章记录编译的过程，后面有需要的人可以看看，https://pengrl.com/p/20044/
