### ISSUE TITLE
编译出错 use of undeclared identifier 'x264_bit_depth'

### ISSUE THREAD

**Issue by jiangjkd** [ksvc/FFmpeg#6]
libavcodec/libx264.c:282:9: error: use of undeclared identifier 'x264_bit_depth'
    if (x264_bit_depth > 8)
        ^
libavcodec/libx264.c:892:9: error: use of undeclared identifier 'x264_bit_depth'
    if (x264_bit_depth == 8)
        ^
libavcodec/libx264.c:894:14: error: use of undeclared identifier 'x264_bit_depth'
    else if (x264_bit_depth == 9)
             ^
libavcodec/libx264.c:896:14: error: use of undeclared identifier 'x264_bit_depth'
    else if (x264_bit_depth == 10)

**Comment by q273255702** [comment]
请问我也报相同的错误，如何解决的

> libavcodec/libx264.c:282:9: error: use of undeclared identifier 'x264_bit_depth'
> if (x264_bit_depth > 8)
> ^
> libavcodec/libx264.c:892:9: error: use of undeclared identifier 'x264_bit_depth'
> if (x264_bit_depth == 8)
> ^
> libavcodec/libx264.c:894:14: error: use of undeclared identifier 'x264_bit_depth'
> else if (x264_bit_depth == 9)
> ^
> libavcodec/libx264.c:896:14: error: use of undeclared identifier 'x264_bit_depth'
> else if (x264_bit_depth == 10)

**Comment by xionghx** [comment]
http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=2a111c99a60fdf4fe5eea2b073901630190c6c93
